---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: bosh-lite

inputs:
  - name: studio-ci
  - name: repo

outputs:
  - name: tag

run:
  path: studio-ci/storyscript-images/tasks/extract-tag.sh
