---
resources:
  - name: schema-repo
    type: git
    source:
      uri: https://github.com/storyscript/database
      branch: master

  - name: auth-repo
    type: git
    source:
      uri: https://github.com/storyscript/auth
      branch: master

  - name: runtime-repo
    type: git
    source:
      uri: https://github.com/storyscript/runtime
      branch: master

  - name: graphql-repo
    type: git
    source:
      uri: https://github.com/storyscript/platform-graphql
      branch: jwt

  - name: synapse-repo
    type: git
    source:
      uri: https://github.com/storyscript/platform-synapse
      branch: master

  - name: gateway-repo
    type: git
    source:
      uri: https://github.com/storyscript/http
      branch: master

  - name: schema-image
    type: docker-image
    source:
      repository: williammartin/schema
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: auth-image
    type: docker-image
    source:
      repository: williammartin/auth
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: runtime-image
    type: docker-image
    source:
      repository: williammartin/runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: graphql-image
    type: docker-image
    source:
      repository: williammartin/graphql
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: synapse-image
    type: docker-image
    source:
      repository: williammartin/synapse
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: gateway-image
    type: docker-image
    source:
      repository: williammartin/gateway
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
- name: build-and-release-schema
  plan:
  - get: schema-repo
    trigger: true
  - put: schema-image
    params: {build: schema-repo}

- name: build-and-release-auth
  plan:
  - get: auth-repo
    trigger: true
  - put: auth-image
    params: {build: auth-repo}

- name: build-and-release-runtime
  plan:
  - get: runtime-repo
    trigger: true
  - put: runtime-image
    params: {build: runtime-repo}

- name: build-and-release-graphql
  plan:
  - get: graphql-repo
    trigger: true
  - put: graphql-image
    params: {build: graphql-repo}

- name: build-and-release-synapse
  plan:
  - get: synapse-repo
    trigger: true
  - put: synapse-image
    params: {build: synapse-repo}

- name: build-and-release-gateway
  plan:
  - get: gateway-repo
    trigger: true
  - put: gateway-image
    params: {build: gateway-repo}
