---
jobs:
- name: release
  public: true
  plan:
    - get: studio
    - get: studio-ci
    - task: release
      file: studio-ci/release.yml
    - put: studio-release
      params:
        repository: studio
    - put: studio-release
      params:
        repository: studio
        only_tag: true
    - task: create-pr
      file: studio-ci/create-pr.yml
      params:
        TOKEN: ((token))

resources:
- name: studio
  type: git
  source:
    uri: git@github.com:storyscript/studio.git
    branch: dev
    private_key: ((private_key))

- name: studio-release
  type: git
  source:
    uri: git@github.com:storyscript/studio.git
    branch: release
    private_key: ((private_key))

- name: studio-ci
  type: git
  source:
    uri: https://github.com/williammartin/studio-ci.git
    branch: master
