---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
  - name: latest-tf-infrastructure
    type: terraform
    source:
      env_name: latest
      backend_type: gcs
      backend_config:
        bucket: dev-platforms
        prefix: terraform/state
        credentials: ((gcp_credentials_json))

  - name: platform-terraform-source
    type: git
    source:
      branch: master
      uri: git@github.com:storyscript/storyscript-platform-terraform.git
      private_key: ((storyscript-infra-ssh-key))

  - name: helm-chart
    type: git
    source:
      branch: master
      uri: git@github.com:storyscript/helm-chart.git
      private_key: ((storyscript-infra-ssh-key))

  - name: pool-repo
    type: git
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      private_key: ((dev_platform_pool_deploy_key))

  - name: latest-platform-update-helm-trigger
    type: git
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      private_key: ((dev_platform_pool_deploy_key))
      paths:
        - .trigger-latest-platform-update-helm # updated by update-terraform

  - name: studio-ci
    type: git
    source:
      branch: master
      uri: https://github.com/storyscript/ci.git

  # <docker-images>
  - name: auth-image
    type: docker-image
    source:
      repository: storyscript/auth
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: creds-image
    type: docker-image
    source:
      repository: storyscript/creds
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: geh-image
    type: docker-image
    source:
      repository: storyscript/geh
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: graphql-image
    type: docker-image
    source:
      repository: storyscript/graphql
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: http-image
    type: docker-image
    source:
      repository: storyscript/http
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: language-image
    type: docker-image
    source:
      repository: storyscript/language
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: nlp-image
    type: docker-image
    source:
      repository: storyscript/nlp
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: router-image
    type: docker-image
    source:
      repository: storyscript/router
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: runtime-image
    type: docker-image
    source:
      repository: storyscript/runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: schema-image
    type: docker-image
    source:
      repository: storyscript/database
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: studio-image
    type: docker-image
    source:
      repository: storyscript/studio
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: worker-image
    type: docker-image
    source:
      repository: storyscript/worker
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}
  # </docker-images>

jobs:
- name: update-helm
  plan:
    - in_parallel:
      - get: studio-ci
      - get: helm-chart
        trigger: true
      - get: latest-platform-update-helm-trigger
        trigger: true
      - get: latest-tf-infrastructure
      # <docker-images>
      - get: auth-image
        trigger: true
      - get: creds-image
        trigger: true
      - get: geh-image
        trigger: true
      - get: graphql-image
        trigger: true
      - get: http-image
        trigger: true
      - get: language-image
        trigger: true
      - get: nlp-image
        trigger: true
      - get: router-image
        trigger: true
      - get: runtime-image
        trigger: true
      - get: schema-image
        trigger: true
      - get: studio-image
        trigger: true
      - get: worker-image
        trigger: true
      # </docker-images>
    - do:
        - task: generate-tls-certs
          file: studio-ci/common-tasks/generate-tls-certs.yml
          params:
            TLS_FULL_CHAIN: ((tls.fullchain))
            TLS_PRIV_KEY: ((tls.privkey))
        - task: generate-env-creds
          file: studio-ci/latest-platform/tasks/generate-env-creds.yml
          params:
            GITHUB_APP_ID: ((github.app_id))
            GITHUB_APP_PRIVATE_KEY: ((github.app_private_key))
            GITHUB_CLIENT_ID: ((github.client_id))
            GITHUB_CLIENT_SECRET: ((github.client_secret))
            SLACK_CLIENT_ID: ((slack.client_id))
            SLACK_CLIENT_SECRET: ((slack.client_secret))
            SLACK_SIGNING_SECRET: ((slack.signing_secret))
            ONEGRAPH_APP_ID: ((onegraph.app_id))
        - task: generate-helm-values
          file: studio-ci/common-tasks/generate-helm-values.yml
          input_mapping:
            platform-terraform: latest-tf-infrastructure
          params:
            DOMAIN: storyscript-ci.com
            APPS_DOMAIN: storyscriptapp-ci.com
            WOLFRAM_APP_ID: ((wolfram_app_id))
            FULLSTORY_ORG_ID: ((studio.fullstory_org_id))
            INTERCOM_APP_ID: ((studio.intercom_app_id))
            SENTRY_DSN: ((studio.sentry_dsn))
        - task: set-latest-tags
          file: studio-ci/latest-platform/tasks/set-latest-tags.yml
        - task: generate-kubeconfig
          file: studio-ci/common-tasks/generate-kubeconfig.yml
          input_mapping:
            platform-terraform: latest-tf-infrastructure
        # TODO: Use chart master here, not release
        - task: helm-upgrade-storyscript
          file: studio-ci/common-tasks/helm-upgrade-storyscript.yml
          input_mapping:
            helmconfig: latest-helmconfig
          params:
            GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
        - try:
            task: whitelist-team
            file: studio-ci/common-tasks/whitelist-team.yml
            timeout: 2m
            input_mapping:
              platform-terraform: latest-tf-infrastructure
            params:
              STORYSCRIPT_INFRA_PASSWORD: ((storyscript-infra-password))
              AUTH_ALLOWLIST_TOKEN: ((auth-allowlist-token))

- name: update-terraform
  plan:
    - in_parallel:
      - get: studio-ci
      - get: pool-repo
      - get: platform-terraform-source
        trigger: true
    - do:
      - put: latest-tf-infrastructure
        params:
          terraform_source: platform-terraform-source/
          vars: &terraform-vars
            credentials: ((gcp_credentials_json))
            project: storyscript-ci
            region: europe-west4
            dns_zone_name: storyscript-ci
            domain: storyscript-ci.com
            apps_dns_zone_name: storyscriptapp-ci
            apps_domain: storyscriptapp-ci.com
            db_username: storyscript
            db_password: storyscript
      - task: trigger-latest-platform-update-helm
        file: studio-ci/latest-platform/tasks/touch-trigger.yml
        input_mapping:
          env-pool: pool-repo
        params:
          TRIGGER_NAME: .trigger-latest-platform-update-helm
      - put: pool-repo
        params:
          repository: updated-env-pool
          rebase: true
