---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
  - name: latest-tf-infrastructure
    type: terraform
    source:
      env_name: latest
      backend_type: gcs
      backend_config:
        bucket: dev-platforms
        prefix: terraform/state
        credentials: ((gcp_credentials_json))

  - name: platform-terraform-source
    type: git
    source:
      branch: master
      uri: git@github.com:storyscript/storyscript-platform-terraform.git
      private_key: ((storyscript-infra-ssh-key))

  - name: studio-ci
    type: git
    source:
      branch: master
      uri: https://github.com/storyscriptinc/ci.git

  - name: schema-image
    type: docker-image
    source:
      repository: storyscript/schema
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: auth-image
    type: docker-image
    source:
      repository: storyscript/auth
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: runtime-image
    type: docker-image
    source:
      repository: storyscript/runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: http-image
    type: docker-image
    source:
      repository: storyscript/http
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: graphql-image
    type: docker-image
    source:
      repository: storyscript/graphql
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: sls-image
    type: docker-image
    source:
      repository: storyscript/sls
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: studio-image
    type: docker-image
    source:
      repository: storyscript/studio
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: wolfram-image
    type: docker-image
    source:
      repository: storyscript/wolfram
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
- name: roll-pods
  plan:
    - in_parallel:
      - get: studio-ci
      - get: schema-image
        trigger: true
      - get: auth-image
        trigger: true
      - get: runtime-image
        trigger: true
      - get: http-image
        trigger: true
      - get: graphql-image
        trigger: true
      - get: sls-image
        trigger: true
      - get: studio-image
        trigger: true
      - get: latest-tf-infrastructure
      - get: wolfram-image
        trigger: true
    - do:
      - task: generate-kubeconfig
        file: studio-ci/latest-platform/tasks/generate-kubeconfig.yml
      - task: roll-pods
        file: studio-ci/latest-platform/tasks/roll-pods.yml
        params:
          GCP_CREDENTIALS_JSON: ((gcp_credentials_json))

- name: update-platform
  plan:
    - in_parallel:
      - get: studio-ci
      - get: platform-terraform-source
        trigger: true
    - do:
      - put: latest-tf-infrastructure
        params:
          terraform_source: platform-terraform-source/
          vars: &terraform-vars
            credentials: ((gcp_credentials_json))
            project: storyscript-ci
            region: europe-west4
            dns_zone_name: storyscript-ci
            domain: storyscript-ci.com
            apps_dns_zone_name: storyscriptapp-ci
            apps_domain: storyscriptapp-ci.com
            db_username: storyscript
            db_password: storyscript
      - task: generate-tls-certs
        file: studio-ci/latest-platform/tasks/generate-tls-certs.yml
        params:
          TLS_FULL_CHAIN: ((tls.fullchain))
          TLS_PRIV_KEY: ((tls.privkey))
      - task: generate-github-credentials
        file: studio-ci/latest-platform/tasks/generate-github-credentials.yml
        params:
          GITHUB_CLIENT_ID: ((github.client_id))
          GITHUB_CLIENT_SECRET: ((github.client_secret))
      - task: generate-helm-values
        file: studio-ci/common-tasks/generate-helm-values.yml
        input_mapping:
          platform-terraform: latest-tf-infrastructure
        params:
          DOMAIN: storyscript-ci.com
          APPS_DOMAIN: storyscriptapp-ci.com
          WOLFRAM_APP_ID: ((wolfram_app_id))
      - task: generate-kubeconfig
        file: studio-ci/latest-platform/tasks/generate-kubeconfig.yml
      - task: helm-upgrade-storyscript
        file: studio-ci/latest-platform/tasks/helm-upgrade-storyscript.yml
        params:
          GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
