---
resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

resources:
  - name: latest-tf-infrastructure
    type: terraform
    source:
      env_name: latest
      backend_type: gcs
      backend_config:
        bucket: dev-platforms
        prefix: terraform/state
        credentials: ((gcp_credentials_json))

  - name: studio-ci
    type: git
    source:
      branch: latest-platform
      uri: https://github.com/storyscriptinc/ci.git

  - name: schema-image
    type: docker-image
    source:
      repository: storyscript/schema
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: auth-image
    type: docker-image
    source:
      repository: storyscript/auth
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: runtime-image
    type: docker-image
    source:
      repository: storyscript/runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: http-image
    type: docker-image
    source:
      repository: storyscript/http
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: graphql-image
    type: docker-image
    source:
      repository: storyscript/graphql
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: sls-image
    type: docker-image
    source:
      repository: storyscript/sls
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: studio-image
    type: docker-image
    source:
      repository: storyscript/studio
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: wolfram-image
    type: docker-image
    source:
      repository: storyscript/wolfram
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
- name: roll-pods
  plan:
    - in_parallel:
      - get: studio-ci
      - get: schema-image
        trigger: true
      - get: auth-image
        trigger: true
      - get: runtime-image
        trigger: true
      - get: http-image
        trigger: true
      - get: graphql-image
        trigger: true
      - get: sls-image
        trigger: true
      - get: studio-image
        trigger: true
      - get: latest-tf-infrastructure
      - get: wolfram-image
        trigger: true
    - do:
      - task: generate-kubeconfig
        file: studio-ci/latest-platform/tasks/generate-kubeconfig.yml
      - task: roll-pods
        file: studio-ci/latest-platform/tasks/roll-pods.yml
        params:
          GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
