---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stedolan/jq

inputs:
  - name: studio-ci
  - name: release

outputs:
  - name: tag-env-var

run:
  path: studio-ci/docker-images/tasks/extract-tag.sh
