---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 18.04

inputs:
  - name: studio-ci
  - name: release

run:
  path: studio-ci/docker-images/tasks/untar-release.sh
