---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: certbot/dns-google

inputs:
  - name: studio-ci

outputs:
  - name: tls-cert

params:
  GCP_CREDENTIALS_JSON: ""
  DOMAINS: ""

run:
  path: studio-ci/tls-certs/tasks/renew-tls-cert.sh
