---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: claranet/gcloud-kubectl-docker

inputs:
  - name: studio-ci
  - name: tls-cert

params:
  GCP_CREDENTIALS_JSON: ""

run:
  path: studio-ci/tls-certs/tasks/update-tls-cert-kubernetes.sh
