---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: alpine/httpie

inputs:
  - name: studio-ci
  - name: tls-cert

params:
  SITE_ID: ""
  NETLIFY_AUTH_TOKEN: ""

run:
  path: studio-ci/tls-certs/tasks/update-tls-cert-netlify.sh
