---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stedolan/jq

inputs:
  - name: studio-ci

outputs:
  - name: github-credentials

params:
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""

run:
  path: studio-ci/latest-platform/tasks/generate-github-credentials.sh
