---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stedolan/jq

inputs:
  - name: studio-ci
  - name: latest-tf-infrastructure
  - name: tls-certs

outputs:
 - name: helmconfig

params:
  DOMAIN: ""
  APPS_DOMAIN: ""
  GITHUB_CLIENT_ID: ""
  GITHUB_CLIENT_SECRET: ""

run:
  path: studio-ci/latest-platform/tasks/generate-helm-values.sh
