---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: bskim45/helm-kubectl-jq
    tag: 3.0.2

inputs:
  - name: studio-ci
  - name: kubeconfig

params:
 GCP_CREDENTIALS_JSON: ""

run:
  path: studio-ci/latest-platform/tasks/roll-pods.sh
