---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: node
    tag: 13

inputs:
  - name: studio-ci
  - name: studio

caches:
  - path: node_modules

run:
  path: studio-ci/studio/tasks/run-units.sh
