---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 18.04

inputs:
  - name: studio-ci
  - name: env-pool

run:
  path: studio-ci/dev-platforms/tasks/check-broken-pool-size.sh
