---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stedolan/jq

inputs:
  - name: studio-ci
  - name: platform-terraform
  - name: github-apps-pool

outputs:
 - name: helmconfig

params:
  DOMAIN: ""

run:
  path: studio-ci/dev-platforms/tasks/generate-helm-values.sh
