---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 18.04

inputs:
  - name: studio-ci

outputs:
  - name: tls-certs

params:
 TLS_FULL_CHAIN: ""
 TLS_PRIV_KEY: ""

run:
  path: studio-ci/dev-platforms/tasks/generate-tls-certs.sh
