---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu
    tag: 18.04

inputs:
  - name: studio-ci

outputs:
  - name: fake-placeholder-env

run:
  path: studio-ci/dev-platforms/tasks/generate-fake-env-for-building-pool.sh
