---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: cloudfoundry/capi
    tag: bosh-lite

inputs:
  - name: studio-ci
  - name: env-pool

outputs:
  - name: updated-env-pool

run:
  path: studio-ci/dev-platforms/tasks/queue-update.sh
