resources:
  - name: studio-ci
    type: git
    source:
      branch: studio-tests
      uri: https://github.com/storyscriptinc/ci.git
  - name: studio
    type: git
    source:
      branch: e2e-in-container
      uri: https://github.com/storyscript/studio.git
  - name: ready-pool
    type: pool
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      pool: dev-platforms
      private_key: ((dev_platform_pool_deploy_key))

jobs:
  - name: run-units
    plan:
      - in_parallel:
        - get: studio-ci
        - get: studio
      - do:
        - task: run-units
          file: studio-ci/studio/tasks/run-units.yml
  - name: run-e2e
    plan:
      - in_parallel:
        - get: studio-ci
        - get: studio
          passed:
            - run-units
        - put: ready-pool
          params:
            acquire: true
      - do:
        - task: run-e2e
          file: studio-ci/studio/tasks/run-e2e.yml
          input_mapping:
            env: ready-pool
          params:
            GITHUB_USERNAME: ((github.username))
            GITHUB_PASSWD: ((github.password))
            GITHUB_TOTP_SECRET: ((github.totp_secret))
        - put: broken-pool
          params:
            remove: ready-pool/
        - put: ready-pool
          params:
            remove: ready-pool/
