resource_types:
  - name: terraform
    type: docker-image
    source:
      repository: ljfranklin/terraform-resource
      tag: latest
  - name: pool-trigger
    type: docker-image
    source:
      repository: cfmobile/pool-trigger

resources:
  - name: platform-terraform
    type: terraform
    source:
      backend_type: gcs
      backend_config:
        bucket: dev-platforms
        prefix: terraform/state
        credentials: ((gcp_credentials_json))

  - name: studio-ci
    type: git
    source:
      branch: master
      uri: https://github.com/storyscriptinc/ci.git
  - name: platform-terraform-source
    type: git
    source:
      branch: master
      uri: git@github.com:storyscript/storyscript-platform-terraform.git
      private_key: ((storyscript-infra-ssh-key))
  - name: ready-pool
    type: pool
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      pool: dev-platforms
      private_key: ((dev_platform_pool_deploy_key))
  - name: broken-pool
    type: pool
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      pool: broken-dev-platforms
      private_key: ((dev_platform_pool_deploy_key))
  - name: broken-pool-trigger
    type: pool-trigger
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      pool: broken-dev-platforms
      private_key: ((dev_platform_pool_deploy_key))
  - name: building-pool
    type: pool
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      pool: building-dev-platforms
      private_key: ((dev_platform_pool_deploy_key))
  - name: updating-pool
    type: pool
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      pool: updating-dev-platforms
      private_key: ((dev_platform_pool_deploy_key))
  - name: updating-pool-trigger
    type: pool-trigger
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      pool: updating-dev-platforms
      private_key: ((dev_platform_pool_deploy_key))
  - name: apps-pool
    type: pool
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      pool: apps
      private_key: ((dev_platform_pool_deploy_key))
  - name: pool-repo
    type: git
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      private_key: ((dev_platform_pool_deploy_key))
  - name: create-dev-platforms-trigger
    type: git
    source:
      branch: master
      uri: git@github.com:williammartin/dev-platform-pool.git
      private_key: ((dev_platform_pool_deploy_key))
      paths:
        - .trigger-dev-platforms-create # updated by check-pool-size
  - name: 5m
    type: time
    source:
      interval: 5m

jobs:
  - name: create-dev-platform
    plan:
      - in_parallel:
        - get: pool-repo
        - get: studio-ci
        - get: platform-terraform-source
        - get: create-dev-platforms-trigger
          trigger: true
      - do:
        - put: apps-pool
          params:
            acquire: true
        - put: building-pool
          params:
            add_claimed: apps-pool/
        - put: platform-terraform
          params:
            env_name_file: apps-pool/name
            terraform_source: platform-terraform-source/
            vars: &terraform-vars
              credentials: ((gcp_credentials_json))
              project: storyscript-ci
              region: europe-west4
              dns_zone_name: storyscript-ci
              domain: storyscript-ci.com
              apps_dns_zone_name: storyscriptapp-ci
              apps_domain: storyscriptapp-ci.com
              db_username: storyscript
              db_password: storyscript
        - task: generate-kubeconfig
          file: studio-ci/common-tasks/generate-kubeconfig.yml
        - task: generate-tls-certs
          file: studio-ci/common-tasks/generate-tls-certs.yml
          params:
            TLS_FULL_CHAIN: ((tls.fullchain))
            TLS_PRIV_KEY: ((tls.privkey))
        - task: generate-helm-values
          file: studio-ci/common-tasks/generate-helm-values.yml
          input_mapping:
            app-credentials: apps-pool
          params:
            DOMAIN: storyscript-ci.com
            APPS_DOMAIN: storyscriptapp-ci.com
            WOLFRAM_APP_ID: ((wolfram_app_id))
        - task: helm-install-storyscript
          file: studio-ci/common-tasks/helm-upgrade-storyscript.yml
          params:
            GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
        - try:
            task: whitelist-team
            file: studio-ci/common-tasks/whitelist-team.yml
            timeout: 30s
            params:
              STORYSCRIPT_INFRA_PASSWORD: ((storyscript-infra-password))
              AUTH_ALLOWLIST_TOKEN: ((auth-allowlist-token))
        - put: ready-pool
          params:
            add: platform-terraform/
        - put: building-pool
          params:
            remove: apps-pool/
        on_failure:
          do:
            - put: platform-terraform
              params:
                action: destroy
                env_name_file: apps-pool/name
                terraform_source: platform-terraform-source/
                vars: *terraform-vars
              get_params:
                action: destroy
            - put: apps-pool
              params:
                release: apps-pool/
            - put: building-pool
              params:
                remove: building-pool/

  - name: update-dev-platform
    plan:
      - in_parallel:
        - get: studio-ci
        - get: platform-terraform-source
        - get: updating-pool-trigger
          trigger: true
      - do:
          - put: updating-pool
            params:
              acquire: true
          - put: platform-terraform
            params:
              env_name_file: updating-pool/name
              terraform_source: platform-terraform-source/
              vars: &terraform-vars
                credentials: ((gcp_credentials_json))
                project: storyscript-ci
                region: europe-west4
                dns_zone_name: storyscript-ci
                domain: storyscript-ci.com
                apps_dns_zone_name: storyscriptapp-ci
                apps_domain: storyscriptapp-ci.com
                db_username: storyscript
                db_password: storyscript
          - task: generate-tls-certs
            file: studio-ci/common-tasks/generate-tls-certs.yml
            params:
              TLS_FULL_CHAIN: ((tls.fullchain))
              TLS_PRIV_KEY: ((tls.privkey))
          - task: generate-helm-values
            file: studio-ci/common-tasks/generate-helm-values.yml
            input_mapping:
              app-credentials: updating-pool
            params:
              DOMAIN: storyscript-ci.com
              APPS_DOMAIN: storyscriptapp-ci.com
              WOLFRAM_APP_ID: ((wolfram_app_id))
          - task: generate-kubeconfig
            file: studio-ci/common-tasks/generate-kubeconfig.yml
          - task: helm-upgrade-storyscript
            file: studio-ci/common-tasks/helm-upgrade-storyscript.yml
            params:
              GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
          - try:
              task: whitelist-team
              file: studio-ci/common-tasks/whitelist-team.yml
              timeout: 30s
              params:
                STORYSCRIPT_INFRA_PASSWORD: ((storyscript-infra-password))
                AUTH_ALLOWLIST_TOKEN: ((auth-allowlist-token))
          - put: updating-pool
            params:
              remove: updating-pool/
        on_failure:
          put: updating-pool
          params:
            release: updating-pool/

  - name: delete-dev-platform
    plan:
      - in_parallel:
        - get: studio-ci
        - get: platform-terraform-source
        - get: broken-pool-trigger
          trigger: true
      - do:
        - put: broken-pool
          params:
            acquire: true
        - put: platform-terraform
          params:
            action: destroy
            env_name_file: broken-pool/name
            terraform_source: platform-terraform-source/
            vars: *terraform-vars
          get_params:
            action: destroy
        - task: delete-gcloud-secrets
          file: studio-ci/dev-platforms/tasks/delete-gcloud-secrets.yml
          params:
            GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
        - put: apps-pool
          params:
            release: broken-pool/
        - put: broken-pool
          params:
            remove: broken-pool/
        on_failure:
          put: broken-pool
          params:
            release: broken-pool/

  - name: check-pool-size
    plan:
      - in_parallel:
        - get: studio-ci
        - get: pool-repo
        - get: 5m
          trigger: true
      - task: check-pool-size
        file: studio-ci/dev-platforms/tasks/check-pool-size.yml
        input_mapping:
          env-pool: pool-repo
        params:
          MIN_UNCLAIMED_COUNT: 2
      - put: pool-repo
        params:
          repository: updated-env-pool
          rebase: true
