---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stedolan/jq

inputs:
  - name: studio-ci
  - name: platform-terraform
  - name: env-creds
  - name: tls-certs

outputs:
 - name: helmconfig

params:
  DOMAIN: ""
  APPS_DOMAIN: ""
  WOLFRAM_APP_ID: ""
  FULLSTORY_ORG_ID: ""
  INTERCOM_APP_ID: ""
  SENTRY_DSN: ""

run:
  path: studio-ci/common-tasks/generate-helm-values.sh
