---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: stedolan/jq

inputs:
  - name: studio-ci
  - name: platform-terraform

outputs:
 - name: kubeconfig

run:
  path: studio-ci/common-tasks/generate-kubeconfig.sh
