---
resources:
  - name: studio-ci
    type: git
    source:
      branch: master
      uri: https://github.com/storyscriptinc/ci.git

  - name: schema-release
    type: github-release
    source:
      owner: storyscript
      repository: database
      access_token: {{storyscript-infra-access-token}}

  - name: schema-repo
    type: git
    source:
      uri: git@github.com:storyscript/database.git
      private_key: ((storyscript-infra-ssh-key))

  - name: auth-release
    type: github-release
    source:
      owner: storyscript
      repository: auth
      access_token: {{storyscript-infra-access-token}}

  - name: auth-repo
    type: git
    source:
      uri: git@github.com:storyscript/auth.git
      private_key: ((storyscript-infra-ssh-key))

  - name: runtime-release
    type: github-release
    source:
      owner: storyscript
      repository: runtime
      access_token: {{storyscript-infra-access-token}}

  - name: runtime-repo
    type: git
    source:
      uri: git@github.com:storyscript/runtime.git
      private_key: ((storyscript-infra-ssh-key))

  - name: graphql-release
    type: github-release
    source:
      owner: storyscript
      repository: graphql
      access_token: {{storyscript-infra-access-token}}

  - name: graphql-repo
    type: git
    source:
      uri: git@github.com:storyscript/graphql.git
      private_key: ((storyscript-infra-ssh-key))

  - name: sls-release
    type: github-release
    source:
      owner: storyscript
      repository: sls
      access_token: {{storyscript-infra-access-token}}

  - name: sls-repo
    type: git
    source:
      uri: git@github.com:storyscript/sls.git
      private_key: ((storyscript-infra-ssh-key))

  - name: worker-release
    type: github-release
    source:
      owner: storyscript
      repository: worker
      access_token: {{storyscript-infra-access-token}}

  - name: worker-repo
    type: git
    source:
      uri: git@github.com:storyscript/worker.git
      private_key: ((storyscript-infra-ssh-key))

  - name: schema-image
    type: docker-image
    source:
      repository: storyscript/schema
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: auth-image
    type: docker-image
    source:
      repository: storyscript/auth
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: runtime-image
    type: docker-image
    source:
      repository: storyscript/runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: graphql-image
    type: docker-image
    source:
      repository: storyscript/graphql
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: sls-image
    type: docker-image
    source:
      repository: storyscript/sls
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: worker-image
    type: docker-image
    source:
      repository: storyscript/worker
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:

  - name: build-schema-latest
    plan:
      - get: schema-repo
        trigger: true
      - put: schema-image
        params:
          build: schema-repo
          tag_as_latest: true

  - name: build-schema-release
    plan:
      - get: studio-ci
      - get: schema-release
        trigger: true
        params:
          include_source_tarball: true
      - task: untar-release
        file: studio-ci/docker-images/tasks/untar-release.yml
        input_mapping: {release: schema-release}
        output_mapping: {source: schema-source}
      - put: schema-image
        params:
          build: schema-source
          tag_file: schema-release/tag

  - name: build-auth-latest
    plan:
      - get: auth-repo
        trigger: true
      - put: auth-image
        params:
          build: auth-repo
          tag_as_latest: true

  - name: build-auth-release
    plan:
      - get: studio-ci
      - get: auth-release
        trigger: true
        params:
          include_source_tarball: true
      - task: untar-release
        file: studio-ci/docker-images/tasks/untar-release.yml
        input_mapping: {release: auth-release}
        output_mapping: {source: auth-source}
      - put: auth-image
        params:
          build: auth-source
          tag_file: auth-release/tag

  - name: build-runtime-latest
    plan:
      - get: runtime-repo
        trigger: true
      - put: runtime-image
        params:
          build: runtime-repo
          tag_as_latest: true

  - name: build-runtime-release
    plan:
      - get: studio-ci
      - get: runtime-release
        trigger: true
        params:
          include_source_tarball: true
      - task: untar-release
        file: studio-ci/docker-images/tasks/untar-release.yml
        input_mapping: {release: runtime-release}
        output_mapping: {source: runtime-source}
      - put: runtime-image
        params:
          build: runtime-source
          tag_file: runtime-release/tag

  - name: build-graphql-latest
    plan:
      - get: graphql-repo
        trigger: true
      - put: graphql-image
        params:
          build: graphql-repo
          tag_as_latest: true

  - name: build-graphql-release
    plan:
      - get: studio-ci
      - get: graphql-release
        trigger: true
        params:
          include_source_tarball: true
      - task: untar-release
        file: studio-ci/docker-images/tasks/untar-release.yml
        input_mapping: {release: graphql-release}
        output_mapping: {source: graphql-source}
      - put: graphql-image
        params:
          build: graphql-source
          tag_file: graphql-release/tag

  - name: build-sls-latest
    plan:
      - get: sls-repo
        trigger: true
      - put: sls-image
        params:
          build: sls-repo
          tag_as_latest: true

  - name: build-sls-release
    plan:
      - get: studio-ci
      - get: sls-release
        trigger: true
        params:
          include_source_tarball: true
      - task: untar-release
        file: studio-ci/docker-images/tasks/untar-release.yml
        input_mapping: {release: sls-release}
        output_mapping: {source: sls-source}
      - put: sls-image
        params:
          build: sls-source
          tag_file: sls-release/tag

  - name: build-worker-latest
    plan:
      - get: worker-repo
        trigger: true
      - put: worker-image
        params:
          build: worker-repo
          tag_as_latest: true

  - name: build-worker-release
    plan:
      - get: studio-ci
      - get: worker-release
        trigger: true
        params:
          include_source_tarball: true
      - task: untar-release
        file: studio-ci/docker-images/tasks/untar-release.yml
        input_mapping: {release: worker-release}
        output_mapping: {source: worker-source}
      - put: worker-image
        params:
          build: worker-source
          tag_file: worker-release/tag
