---
resources:

  - name: studio-ci
    type: git
    source:
      branch: master
      uri: https://github.com/storyscriptinc/ci.git

  - name: schema-release
    type: github-release
    source:
      owner: storyscript
      repository: database
      access_token: {{access-token}}

  - name: auth-release
    type: github-release
    source:
      owner: storyscript
      repository: auth
      access_token: {{access-token}}

  - name: runtime-release
    type: github-release
    source:
      owner: storyscript
      repository: runtime
      access_token: {{access-token}}

  - name: graphql-release
    type: github-release
    source:
      owner: storyscript
      repository: graphql
      access_token: {{access-token}}

  - name: synapse-release
    type: github-release
    source:
      owner: storyscript
      repository: platform-synapse
      access_token: {{access-token}}

  - name: gateway-release
    type: github-release
    source:
      owner: storyscript
      repository: http
      access_token: {{access-token}}

  - name: sls-release
    type: github-release
    source:
      owner: storyscript
      repository: sls
      access_token: {{access-token}}

  - name: schema-image
    type: docker-image
    source:
      repository: storyscript/schema
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: auth-image
    type: docker-image
    source:
      repository: storyscript/auth
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: runtime-image
    type: docker-image
    source:
      repository: storyscript/runtime
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: graphql-image
    type: docker-image
    source:
      repository: storyscript/graphql
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: synapse-image
    type: docker-image
    source:
      repository: storyscript/synapse
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: gateway-image
    type: docker-image
    source:
      repository: storyscript/gateway
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

  - name: sls-image
    type: docker-image
    source:
      repository: storyscript/sls
      username: {{dockerhub-username}}
      password: {{dockerhub-password}}

jobs:
- name: build-and-release-schema
  plan:
    - get: studio-ci
    - get: schema-release
      trigger: true
      params:
        include_source_tarball: true
    - task: untar-release
      file: studio-ci/docker-images/tasks/untar-release.yml
      input_mapping: {release: schema-release}
      output_mapping: {source: schema-source}
    - put: schema-image
      params:
        build: schema-release/source
        tag_file: schema-release/tag
        tag_as_latest: true

- name: build-and-release-auth
  plan:
    - get: studio-ci
    - get: auth-release
      trigger: true
      params:
        include_source_tarball: true
    - task: untar-release
      file: studio-ci/docker-images/tasks/untar-release.yml
      input_mapping: {release: auth-release}
      output_mapping: {source: auth-source}
    - put: auth-image
      params:
        build: auth-release/source
        tag_file: auth-release/tag
        tag_as_latest: true

- name: build-and-release-runtime
  plan:
    - get: studio-ci
    - get: runtime-release
      trigger: true
      params:
        include_source_tarball: true
    - task: untar-release
      file: studio-ci/docker-images/tasks/untar-release.yml
      input_mapping: {release: runtime-release}
      output_mapping: {source: runtime-source}
    - put: runtime-image
      params:
        build: runtime-release/source
        tag_file: runtime-release/tag
        tag_as_latest: true

- name: build-and-release-graphql
  plan:
    - get: studio-ci
    - get: graphql-release
      trigger: true
      params:
        include_source_tarball: true
    - task: untar-release
      file: studio-ci/docker-images/tasks/untar-release.yml
      input_mapping: {release: graphql-release}
      output_mapping: {source: graphql-source}
    - put: graphql-image
      params:
        build: graphql-release/source
        tag_file: graphql-release/tag
        tag_as_latest: true

- name: build-and-release-synapse
  plan:
    - get: studio-ci
    - get: synapse-release
      trigger: true
      params:
        include_source_tarball: true
    - task: untar-release
      file: studio-ci/docker-images/tasks/untar-release.yml
      input_mapping: {release: synapse-release}
      output_mapping: {source: synapse-source}
    - put: synapse-image
      params:
        build: synapse-release/source
        tag_file: synapse-release/tag
        tag_as_latest: true

- name: build-and-release-gateway
  plan:
    - get: studio-ci
    - get: gateway-release
      trigger: true
      params:
        include_source_tarball: true
    - task: untar-release
      file: studio-ci/docker-images/tasks/untar-release.yml
      input_mapping: {release: gateway-release}
      output_mapping: {source: gateway-source}
    - put: gateway-image
      params:
        build: gateway-release/source
        tag_file: gateway-release/tag
        tag_as_latest: true

- name: build-and-release-sls
  plan:
    - get: studio-ci
    - get: sls-release
      trigger: true
      params:
        include_source_tarball: true
    - task: untar-release
      file: studio-ci/docker-images/tasks/untar-release.yml
      input_mapping: {release: sls-release}
      output_mapping: {source: sls-source}
    - put: sls-image
      params:
        build: sls-source
        tag_file: sls-release/tag
        tag_as_latest: true
