resource_types:
  - name: tls-trigger
    type: docker-image
    source:
      repository: anukulsangwan/tls-trigger-resource


resources:
  - name: studio-ci
    type: git
    source:
      branch: master
      uri: https://github.com/storyscript/ci.git

  - name: prod-cert-trigger
    type: tls-trigger
    check_every: 24h
    source:
      domain: storyscript.com
      expires_in: 14


jobs:
  - name: renew-prod-cert
    plan:
      - get: studio-ci
      - get: prod-cert-trigger
        trigger: true
      - task: renew-tls-cert
        file: studio-ci/tls-certs/tasks/renew-tls-cert.yml
        params:
          GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
          DOMAINS: "storyscript.com, *.storyscript.com,
                    storyscript.io, *.storyscript.io,
                    storyscri.pt, *.storyscri.pt"
      - task: update-tls-cert-netlify
        file: studio-ci/tls-certs/tasks/update-tls-cert-netlify.yml
        params:
          SITE_ID: ((netlify.site_id))
          NETLIFY_AUTH_TOKEN: ((netlify.auth_token))
      - task: update-tls-cert-kubernetes
        file: studio-ci/tls-certs/tasks/update-tls-cert-kubernetes.yml
        params:
          GCP_CREDENTIALS_JSON: ((gcp_credentials_json))
